apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::464599248654:role/eks-cluster-WorkerNodesRole-19TMWCYTLGPZQ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-02-15T00:49:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2015"
  uid: 1a5ab8a8-401d-44b6-bd23-de5974f97d30
